### PR TITLE
Quote dollar signs when not by themself

### PR DESCRIPTION
**Pull request by BolunThompson**
Analogous to binpash/shasta#3. There’s the broader question of whether we can remove the (libdash, presumably) pretty printer and instead use the shasta pretty printer, but this copies the change from the shasta printer to libdash.

### CODE REVIEW

**Comment by mgree** [comment]
This looks good, but for some reason CI hasn't run (and I'd like to confirm that all tests pass before merging!). :thinking:

**Comment by angelhof** [comment]
@mgree could it be that the branch is not a libdash branch? I am struggling to understand why tests didn't run here...

**Comment by mgree** [comment]
Yeah, no idea. I have "Require approval for first-time contributors" turned on but... :thinking: :thinking: :thinking: 

If you can run tests locally and they pass, I'm okay to merge and see if things fail on main.

**Comment by BolunThompson** [comment]
After making the equivalent change in the ocaml pretty printer, all the tests pass on my machine: https://gist.github.com/BolunThompson/b073fe50dbd3b4995f26bd564b5cc546

**Pull request merged**
